@startuml Login Flowchart

skinparam activity {
    BackgroundColor lightblue
    
    StartColor green
    EndColor red
    
    diamondBackgroundColor lightgreen
}

(*) --> "Recieve login data"

if "Ip not blocked" then
    if "Email exists" then
        if "Password matches" then
            if "User has logged in before from ip" then
                -->[true] "Generate token"
                --> "Return token"
                --> (*)
            else
                -->[false] 2FA
            end if 
        else
            -->[false] "Throw Login failed"
        end if
    else
      -->[false] "Throw Login failed"

    end if 
else 
 --> "Throw Forbidden"
end if
@enduml
