@startuml Login Flowchart

(*) --> "Recieve login data"

if "Ip not blocked " then
    if "Email exists" then
        if "Password matches" then
            if "User has logged in before from ip" then
                -->[true] "Generate token"
                --> "Return token"
                --> (*)
            else
                -->[false] Send verification code to User
                --> User enters verification code
                if "Verification code match" then
                -->[true] "Generate token"
                else
                -->[false] "Throw Login failed"
                end if
            end if 
        else
            -->[false] "Throw Login failed"
        end if
    else
      -->[false] "Throw Login failed"

    end if 
else 
 --> "Throw Forbidden"
end if
@enduml
