@startuml Login Flowchart

skinparam activity {
    BackgroundColor lightblue
    
    StartColor green
    EndColor red
    
    diamondBackgroundColor lightgreen
}

(*) --> "Recieve login data"

if "Ip not blocked" then
    if "Email exists" then
        if "Account is locked" then
            if "Account is verified" then
                if "Password matches" then
                    if "User has logged in before from ip" then
                        -->[true] "Generate token"
                        --> "Return token"
                        --> (*)
                    else
                        -->[false] Send verification code to User
                        --> User enters verification code
                        if "Verification code match" then
                        -->[true] "Generate token"
                        else
                        -->[false] "Return wrong credentials message"
                        end if
                    end if 
                else
                    -->[false] "Return wrong credentials message"
                end if
            else
                -->[false] "Return account is not verified message"
            end if
        else
            -->[true] "Return Account is locked message"
        end if
    else
      -->[false] "Return wrong credentials message"

    end if 
else 
 --> "Return Forbidden message"
end if
@enduml
