@startuml ERD
left to right direction

entity "UserPasswords" as up{
    ID int (PK)
    UsersID int (FK)
    --
    HashedPassword varchar(200)
    Salt varchar(200)
}

entity "SecretKeyCounter" as sk {
    ID int (PK)
    UsersID int (FK)
    --
    SecretKey varchar(200)
    Counter BIGINT
}

entity Users {
    ID int (PK)
    --
    Email varchar(100)
    IsVerified bit
    FirstName varchar(50)
    LastName varchar(50)
    PhoneNumber varcher(20)
    FailedTries int
    IsLocked bit
    LockedDate datetime
}
entity "UserLocation" as vul {
    ID int (PK)
    UsersID int
    --
    IP string(50)
    UserAgent varchar(256)
    Successful bit
    CreateDate datetime
}

Users::ID"      1" -- "*"vul::UsersID

up::UserID"1" -- "1"Users::ID

sk::UserID"1" -- "1"Users::ID


@enduml