@startuml ERD
left to right direction

entity "UserPasswords" as up{
    ID int (PK)
    UsersID int (FK)
    --
    HashedPassword varchar(200)
    Salt varchar(200)
}

entity Users {
    ID int (PK)
    --
    Email varchar(100)
    HashedVerification varchar(200)
    IsVerified bit
    FirstName varchar(50)
    LastName varchar(50)
    PhoneNumber varcher(20)
    FailedTries int
    IsLocked bit
    LockedDate datetime
}
entity "VerifiedUserLocations" as vul {
    ID int (PK)
    UsersID int (FK)
    --
    IP binary(16)
    IPType byte
    UserAgent varchar(256)
}

Users::ID"      1" -- "*"vul::UsersID

up::UserID"1" -- "1"Users::ID


@enduml